services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - POSTGRES_DB=pixabay_favorites
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - JWT_SECRET=${JWT_SECRET}
      - PIXABAY_API_KEY=${PIXABAY_API_KEY}
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pixabay_favorites
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: