services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - POSTGRES_DB=pixabay_favorites
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - JWT_SECRET=ba286d7af1cf39f06c06302429c79a9e9e28ba5d41e429b9d429dbd1852191d7
      - PIXABAY_API_KEY=39688808-ea81d6685b8e61ec339adf86f
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist  # Don't sync the dist folder

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pixabay_favorites
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: